### ISSUE TITLE
第 20 题：BFC、垂直居中、响应式布局

### ISSUE THREAD

**Issue by ravencrown** [ravencrown/noteBook#35]
### BFC 块级格式化上下文

它会创建一个特殊的区域，在这个区域中，只有 block box 参与布局。而 BFC 的一套特点和规则就规定了在这个特殊的区域中如何进行布局，如何进行定位，区域内元素的相互关系和相互作用。这个特殊的区域不受外界影响。

**如何形成 BFC**

那么什么样的情况会创建一个 BFC 呢？MDN 总结如下：

- 根元素或其他包含它的元素
- 浮动元素 (元素的 float 不是 none)
- 绝对定位元素 (元素具有 position 为 absolute 或 fixed)
- 内联块 (元素具有 display: inline-block)
- 表格单元格 (元素具有 display: table-cell，HTML 表格单元格默认属性)
- 表格标题 (元素具有 display: table-caption, HTML 表格标题默认属性)
- 具有 overflow 且值不是 visible 的块元素
- display: flow-root 的元素
- column-span: all 的元素

**BFC 决定了什么**

我们上面谈到了 BFC 的一套规则，那么这些规则都有哪些呢？

- 内部的 box 将会独占宽度，且在垂直方向，一个接一个排列
- box 垂直方向的间距由 margin 属性决定，但是同一个 BFC 的两个相邻 box 的 margin 会出现边距折叠现象
- 每个 box 水平方向上左边缘，与 BFC 左边缘相对齐，即使存在浮动也是如此
- BFC 区域不会与浮动元素重叠，而是会依次排列
- BFC 区域内是一个独立的渲染容器，容器内元素和 BFC 区域外元素不会形成任何干扰
- 浮动元素的高度也参与到 BFC 高度的计算当中

从这些规则中，我们至少能总结出一些关键要点，比如：

- 边距折叠
- 清除浮动
- 自适应多栏布局

### 多种方式实现居中

“实现居中”也是一道必考题。参考代码：

```html
<style>
.wp {
    border: 1px solid red;
    width: 300px;
    height: 300px;
}

.box {
    background: green;    
}

.box .fixed-size {
    width: 100px;
    height: 100px;
}
</style>

<body>
    <div class="wp">
       <div class="box fixed-size">text</div>
    </div>
</body>

```

**如图，如何让绿色的块水平居中呢？**

![image](https://user-images.githubusercontent.com/9835391/61843797-ab7bee80-aecf-11e9-9c73-a092f06dcf9c.png)

**居中元素定宽高方式一：absolute + 负 margin**

```css
.wp {
    position: relative;
}
.box {
    position: absolute;;
    top: 50%;
    left: 50%;
    margin-left: -50px;
    margin-top: -50px;
}
```

**居中元素定宽高方式二：absolute + margin auto**

这种方式将设置各个方向的距离都是 0，此时配合 margin 为 auto，就可以在各个方向上居中了。

```css
.wp {
    position: relative;
}
.box {
    position: absolute;;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    margin: auto;
}

```

**居中元素定宽高方式三：absolute + calc**

```css
.root {
    position: relative;
}
.textBox {
    position: absolute;;
    top: calc(50% - 50px);
    left: calc(50% - 50px);
}
```

**居中元素不定宽高**

```html
<style>
.wp {
    border: 1px solid red;
    width: 300px;
    height: 300px;
}

.box {
    background: green;    
}
</style>

<body>
    <div class="wp">
       <div class="box ">text</div>
    </div>
</body>
```

**居中元素不定宽高解决方式一：absolute + transform**

不定宽高时，利用 CSS3 新增的 transform，transform 的 translate 属性也可以设置百分比，这个百分比是相对于自身的宽和高，因此可以将 translate 设置为 ﹣50%：

```css
.wp {
    position: relative;
}
.box {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```

**居中元素不定宽高解决方式二：lineheight**

把 box 设置为行内元素，通过 text-align 也可以做到水平居中，同时通过 vertical-align 做到垂直方向上的居中，代码如下：

```css
.wp {
    line-height: 300px;
    text-align: center;
    font-size: 0px;
}
.box {
    font-size: 16px;
    display: inline-block;
    vertical-align: middle;
    line-height: initial;
    text-align: left; /* 修正文字 */
}
```

**居中元素不定宽高解决方式三：table**

其实历史上 table 经常被用来做页面布局，这么做的缺点是会增加很多冗余代码，并且性能也不友好。不过处理居中问题，它可是能手：

```css
.wp {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
}
.box {
    display: inline-block;
}

```

**居中元素不定宽高解决方式四：flex**

```css
.wp {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

**居中元素不定宽高解决方式四：grid**

grid 布局非常超前，虽然兼容性不好，但是能力超强：

```css
.wp {
    display: grid;
}
.box {
    align-self: center;
    justify-self: center;
}

```

我们总结一下：

- PC 端有兼容性要求，宽高固定，推荐 absolute + 负 margin
- PC 端有兼容要求，宽高不固定，推荐 css-table
- PC 端无兼容性要求，推荐 flex
- 移动端推荐使用 flex

最后整理一个列表：

![image](https://user-images.githubusercontent.com/9835391/61844306-87b9a800-aed1-11e9-94e6-c4d5cc0d605e.png)

### 上帝视角——响应式布局适配方案

我们首先来梳理一下响应式布局的几种典型方案：

- 传统 float 浮动布局
- 相对单位布局
- 媒体查询
- 基于相对单位 rem 的 flexible 布局
- flex 布局
- grid 布局
- 借助 JavaScript

相对单位布局比较容易理解，梳理 CSS 中的相对单位有：

- em：em 相对于当前元素或当前元素继承来的字体的大小
- rem：rem 相对于根节点（html）的字体大小
- vw：vw 相对于视口宽度，100vw 就相当于一个视口宽度，1vw等于视口宽度的1%。
- vh：vh 同理，1vh 表示视口高度的 1/100，100vh 就是一个视口高度，1vh等于视口高度的1%
- vmin：相对于视口的宽度或高度中较小的那个，也就是 1vw 和 1vh 取最小，（Math.min(1vw, 1vh)）
- vmax：vmax 相对于视口的宽度或高度中较大的那个，（Math.max(1vw, 1vh)）
- %：
- calc()：也是一个响应式布局神器，它使得 CSS 有了运算的能力：

在进入分析前，我们先罗列一下其他关于响应式布局的概念：

- 屏幕分辨率
- 像素
- PPI（Pixel Per Inch）：每英寸包括的像素数
- DPI（Dot Per Inch）：即每英寸包括的点数
- 设备独立像素
- 设备像素比（dpr）
- Meta Viewport

```html
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
```

禁用了用户缩放功能，使页面宽度和设备宽度对齐，一般这种操作也是移动端的响应式适配的标配。
